apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app

spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1

  template:
    metadata:
      labels:
        app: flask-app

    spec:
      volumes:
        - name: volume-flask
          hostPath:
            path: /workdir/flask_app
            type: Directory

      containers:
        - name: flask
#          stdin: true
#          tty: true
          image: flask-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: SERVICE_PORT
              value: "5000"
            - name: JINA_PORT
              value: "49000"
            - name: JINA_HOST
              value: jina-gateway-svc
          volumeMounts:
            - mountPath: /app
              name: volume-flask
          command: ['python', 'app.py']
#          resources:
#            requests:
#              memory: "64Mi"
#              cpu: "50m"
#            limits:
#              memory: "128Mi"
#              cpu: "100m"