apiVersion: v1
kind: Service
metadata:
  name: flask-jina-gateway-svc
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    name: flask
    protocol: TCP
  - port: 55558
    targetPort: 55558
    name: gateway-port-in
    nodePort: 30528
  - port: 55555
    targetPort: 55555
    name: gateway-port-out
    nodePort: 30704
  - port: 60000
    targetPort: 60000
    name: gateway-port-ctrl
    nodePort: 31696
  - port: 49000
    targetPort: 49000
    name: gateway-port-expose
    nodePort: 30123
  selector:
    app: flask-jina-gateway

